### ISSUE TITLE
Building on my Linux box requires -lm and -ldl

### ISSUE THREAD

**Issue by dansanderson** [MEGA65/m65dbg#25]
Sorry for dropping this in an issue and not a PR, I'm rushing: I noticed that on my Arch Linux box, I needed explicit LDFLAGS for gcc math libraries:

```
LDFLAGS+=-lpng -lm -ldl
```

Without these the link failed looking for the pow() function.

**Comment by MJoergen** [comment]
In this PR https://github.com/MEGA65/m65dbg/pull/27 I added "-lm", which was sufficient on my box (Ubuntu 22.04 LTS).

**Comment by gurcei** [comment]
Sorry for neglecting my tickets for so long, and thank you @MJoergen for resolving the matter, will close this ticket off then :)
