### ISSUE TITLE
add some metrics

### ISSUE THREAD

**Issue by gurcei** [MEGA65/m65dbg#3]
Following on from this forum thread post:

https://groups.google.com/d/msg/c65gs-development/FESl92s4vEM/ssr_u0cDAQAJ

We've got some concerns about the speed of debugging over the USB serial port interface, so it would be good to get some accurate measurements on where the delays are occurring.

I was thinking of printing out some debug timestamp information at key moments:
- upon pressing ENTER key on a command
- prior to sending out the command packet
- upon receiving the 1st byte of the result packet
- upon receiving the last byte of the result packet
- upon completion of my visual processing of the result packet

**Comment by gardners** [comment]
The uart monitor itself is a simple hardware state machine, that spends most of its time waiting for the serial port to be able to accept the next byte (it is clocked at 48MHz like the CPU).  Thus it is highly likely that the USB part of things is the source of delay.  There is a mechanism to write a character to the USB serial monitor from the MEGA65's CPU, so you could write a character to the serial port, and also toggle an IO line or display something on the screen, and time the difference that way.

**Comment by gurcei** [comment]
I think gardners did a bunch of stuff to speed this up, years ago. Think speed is fine these days, closing.
