### ISSUE TITLE
load/save commands

### ISSUE THREAD

**Issue by gurcei** [MEGA65/m65dbg#4]
I'd like to:
- create a "load {binfile} {addr}" method to load a binary file direct to memory
- create a "save {binfile} {addr} {count}" method to save a chunk of memory to a binary file on your pc

I'm hoping these functions will help me when making comparisons between original rom/.bin contents and what's found in the memory after loading from the sd-card.

**Comment by Ben-401** [comment]
yes please, i want one.

**Comment by gurcei** [comment]
save is now implemented, I'll get to work on load another time

**Comment by gurcei** [comment]
Load seems to be working now too, can't remember when I did it, but it's done :) Closing the ticket
