### ISSUE TITLE
settings/init files

### ISSUE THREAD

**Issue by gurcei** [MEGA65/m65dbg#6]
It might be nice to have a "~/.m65dbg_settings" file to preserve configuration information, such as the serial-port device name.

Maybe a "~/.m65dbg_init" file would be nice one day too, as a place to store:
- your preferred initialisation steps (eg, "autocls 1", "autowatch 1")
- a place to store user-defined functions/macros that you need regularly

**Comment by Ben-401** [comment]
good idea, i suggest it be called m65dbgrc to hold both types of information namely config and steps/macros.
one idea is that upon execution of this file is missing, a minimal rc-file is written out.
alternatively, an rc-file is packaged with the repo and users directed to setup/configure this file prior to using

**Comment by gurcei** [comment]
Yep, this seems to be done. I believe you can now add a global "~/.m65dbg_init", and/or a local ".m65dbg_init" in your project's base-path too. Will close this one off.
